"""Initial migration

Revision ID: f4a12e2ef468
Revises: 
Create Date: 2026-02-03 13:10:40.506017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a12e2ef468'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('job_relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidate_profiles_candidate_id'), 'candidate_profiles', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_email'), 'candidate_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_name'), 'candidate_profiles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profiles_name'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_email'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_candidate_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
